### ISSUE TITLE
淘宝搜索 : 看鬼故事 是什么功能?

### ISSUE THREAD

**Issue by ruizgo** [ffffffff0x/Digital-Privacy#10]
RT

**Comment by No-Github** [comment]
19年底的一个小功能，查看历史账单，现在没了
- https://post.smzdm.com/p/apzk8xd0/

过几天更新下readme里面过期的链接

**Comment by badboybxonex** [comment]
-- - [ ] Do you know satay nadella cus I did speak in private sector now I'm telling you the truth nothing but the truth about basically ring the British gambling commission and when I reported my £250.000  being changed to both teams to score all I did was put &10 on 16 favourites in the first round of the champions league football night November 3rd but I picked 1 game to draw which was 13/2  7/1 for argument sake I wasn't expecting to win when he added both teams to score but there not clever enough because 17.28 pm uk time I put my bet on and anyway I was shocked at the returns. It thinking about £[0 on 16 teams to win would be 30 40,000 back and then you've got to times that by 71 which brings you to 250 grand know if I pick both teams to score I have a game as well that's where I would discredit both the Acca and sky there because there result the odds were different and the payout would be 1,000,000+ so anyway when I went to the gamblers commissioner they was only gambling commission of site they was advertising on their webpage sky bet paid £1 million out last year for duplicate accounts so that give me a bit of roof but because of the Covid I didn't hear of the action fraud please +4 months Richard appreciate because life matter before money but karma karma is a big and strong word which works all the time if you don't anything wrong to no one yeah￼￼￼ so I had so I had a call last week last Saturday night with her a nice lady and her family I think she's Philippine and her daughters birthday I think and she was sorting my order out Birch that day I had to turn my devices off while on the phone whilst talking to somebody at Microsoft because they said they could tell somebody was asking me so basically I can't I don't know what to say if you don't wanna believe me you can come to my house or send someone in Nottingham are you know she come and see me at my home and I'll prove who I am yeah and go to NGNG2 no NG24FT meadows Nottingham 2 doors to left side of the rainbow dentist now this nice family I believe working for Microsoft and I said I need to hand this box which is in new condition still bearing in mind I can't argue on it there when I was doing my wards and running I want some things that basically I was getting looked after I think if you speak to the CEO because ultimately knows what went off and what happened to me so the actors seen all this information because of these Apple devices and he's even downloaded all my pictures everything now if you don't want to get if you want to get into it for the action vote please they will corroborate what I told you yes my name is Carl Maurice brown 20/01/1975 Ng119fx 9 Avebury Close Clifton and I started the Microsoft 360 £79 for year if possible pay over 12 months but there's nothing worse than NOT BEING A MAN WHOS DONE A FULL DAY WORK FEEL VERY GOOD AND I MISS THAT SO MY PLAN 1 MONTH FREE BUT LAST WEEK I THINK EVEN WHEN SOMEONE HIGH UP IM NOT 100% who I'm talking with but I've got nothing to hide so what Microsoft did was show there vulnerable customers compassion and loyalty just look who paid all the ultimate subscription me with MasterCard debit Santander end 2536 last card but mostly paid with my o2 phone bill cus he already spend about £100 on my debit card and no one would listen too me but I said to satay nadella what Evers on my Xbox one Xdt is mine cus data protection I would be taking I know 3 gambling sites who have let the hacker use my account with a electron card in my name his name is John Appleseed extremely uglier than me but looks aren't everything I can't hide behind a monitor ruining peoples lives and I can't believe I was speaking to Ben who nadella told me to ring Ben philaphine nice guy younger than me well he.could see what I was rewarded Xbox rewards and baring in mind I trusted what the Microsoft guy told me so I was on a new iPad pro which I want to change ASAP also my I phone 12 pro max security is discusting so I have bens ID no so are you here to help cus I can't even log into the Xbox one now with my new outlook account carlo
